- id: ID_i34nlyk9
  name: DJZHANG_Profile
  generalConfig:
    mode: rule
    mixed-port: 20122
    allow-lan: false
    log-level: info
    interface-name: ""
  advancedConfig:
    port: 0
    socks-port: 0
    secret: ID_gji8aqyt
    external-controller: 127.0.0.1:20123
    external-ui: ""
    external-ui-url: ""
    profile:
      store-cache: true
      store-fake-ip: true
      store-rdrc: false
    domain_strategy: ipv4_only
    tcp-fast-open: false
    tcp-multi-path: false
    udp-fragment: false
    sniff: true
    sniff-override-destination: false
  tunConfig:
    enable: false
    stack: Mixed
    auto-route: true
    interface-name: ""
    mtu: 9000
    strict-route: true
    endpoint-independent-nat: false
    inet4-address: 172.19.0.1/30
    inet6-address: fdfe:dcba:9876::1/126
  dnsConfig:
    enable: true
    fakeip: false
    strategy: ipv4_only
    local-dns: https://223.5.5.5/dns-query
    remote-dns: tls://8.8.8.8
    resolver-dns: 223.5.5.5
    remote-resolver-dns: 8.8.8.8
    final-dns: remote-dns
    local-dns-detour: ðŸŽ¯ Direct
    remote-dns-detour: ðŸš€ Select
    fake-ip-range-v4: 198.18.0.1/16
    fake-ip-range-v6: fc00::/18
    fake-ip-filter:
      - .lan
      - .localdomain
      - .example
      - .invalid
      - .localhost
      - .test
      - .local
      - .home.arpa
      - .msftconnecttest.com
      - .msftncsi.com
    disable-cache: false
    disable-expire: false
    independent-cache: false
    client-subnet: ""
  proxyGroupsConfig:
    - id: ID_v02ympgs
      tag: ðŸš€ Select
      type: selector
      proxies:
        - id: ID_dw6m6m87
          type: built-in
          tag: ðŸŽˆ Auto
      use:
        - ID_7slmx42f
      url: ""
      interval: 300
      tolerance: 150
      filter: ""
    - id: ID_dw6m6m87
      tag: ðŸŽˆ Auto
      type: urltest
      proxies: []
      use:
        - ID_7slmx42f
      url: https://www.gstatic.com/generate_204
      interval: 300
      tolerance: 150
      filter: ""
    - id: ID_f5ckyhbd
      tag: ðŸŽ¯ Direct
      type: selector
      proxies:
        - id: direct
          type: built-in
          tag: direct
        - id: block
          type: built-in
          tag: block
      use: []
      url: ""
      interval: 300
      tolerance: 150
      filter: ""
    - id: ID_6czzb8yz
      tag: ðŸ›‘ Block
      type: selector
      proxies:
        - id: block
          type: built-in
          tag: block
        - id: direct
          type: built-in
          tag: direct
      use: []
      url: ""
      interval: 300
      tolerance: 150
      filter: ""
    - id: ID_p1ei0ifn
      tag: ðŸŸ Fallback
      type: selector
      proxies:
        - id: ID_v02ympgs
          type: built-in
          tag: ðŸš€ Select
        - id: ID_f5ckyhbd
          type: built-in
          tag: ðŸŽ¯ Direct
      use: []
      url: ""
      interval: 300
      tolerance: 150
      filter: ""
    - id: ID_clx6fwzh
      tag: GLOBAL
      type: selector
      proxies:
        - id: direct
          type: built-in
          tag: direct
        - id: block
          type: built-in
          tag: block
        - id: ID_v02ympgs
          type: built-in
          tag: ðŸš€ Select
        - id: ID_dw6m6m87
          type: built-in
          tag: ðŸŽˆ Auto
        - id: ID_f5ckyhbd
          type: built-in
          tag: ðŸŽ¯ Direct
        - id: ID_6czzb8yz
          type: built-in
          tag: ðŸ›‘ Block
        - id: ID_p1ei0ifn
          type: built-in
          tag: ðŸŸ Fallback
      use: []
      url: ""
      interval: 300
      tolerance: 150
      filter: ""
  rulesConfig:
    - id: ID_0qb5a7en
      type: inline
      payload: |-
        {
          "protocol": "dns",
          "port": 53
        }
      proxy: dns-out
      ruleset-name: ""
      ruleset-format: ""
      download-detour: ""
      invert: false
    - id: ID_y6zjvynx
      type: clash_mode
      payload: direct
      proxy: direct
      ruleset-name: ""
      ruleset-format: ""
      download-detour: ""
      invert: false
    - id: ID_r3p11lt1
      type: clash_mode
      payload: global
      proxy: GLOBAL
      ruleset-name: ""
      ruleset-format: ""
      download-detour: ""
      invert: false
    - id: ID_eg241qcz
      type: inline
      payload: |-
        {
          "network": "udp",
          "port": 443
        }
      proxy: ðŸ›‘ Block
      ruleset-name: ""
      ruleset-format: ""
      download-detour: ""
      invert: false
    - id: ID_jrtvw3po
      type: rule_set_url
      payload: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/category-ads-all.srs
      proxy: ðŸ›‘ Block
      ruleset-name: CATEGORY-ADS
      ruleset-format: binary
      download-detour: ðŸŽ¯ Direct
      invert: false
    - id: ID_evrz33hz
      type: ip_is_private
      payload: ""
      proxy: ðŸŽ¯ Direct
      ruleset-name: ""
      ruleset-format: ""
      download-detour: ""
      invert: false
    - id: ID_rmfd2p3b
      type: rule_set_url
      payload: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geoip/cn.srs
      proxy: ðŸŽ¯ Direct
      ruleset-name: GEOIP-CN
      ruleset-format: binary
      download-detour: ðŸŽ¯ Direct
      invert: false
    - id: ID_r1rpw1ew
      type: rule_set_url
      payload: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/cn.srs
      proxy: ðŸŽ¯ Direct
      ruleset-name: GEOSITE-CN
      ruleset-format: binary
      download-detour: ðŸŽ¯ Direct
      invert: false
    - id: ID_17dfmbcy
      type: rule_set_url
      payload: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/geolocation-!cn.srs
      proxy: ðŸš€ Select
      ruleset-name: GEOLOCATION-!CN
      ruleset-format: binary
      download-detour: ðŸŽ¯ Direct
      invert: false
    - id: ID_qok2nxns
      type: final
      payload: ""
      proxy: ðŸŸ Fallback
      ruleset-name: ""
      ruleset-format: ""
      download-detour: ""
      invert: false
  dnsRulesConfig:
    - id: ID_m5ocyin5
      type: outbound
      payload: any
      server: local-dns
      invert: false
      disable-cache: true
      ruleset-name: ""
      ruleset-format: ""
      download-detour: ""
      client-subnet: ""
    - id: ID_ml9witsj
      type: fakeip
      payload: ""
      server: fakeip-dns
      invert: false
      disable-cache: false
      ruleset-name: ""
      ruleset-format: ""
      download-detour: ""
      client-subnet: ""
    - id: ID_va9tga1g
      type: clash_mode
      payload: direct
      server: local-dns
      invert: false
      disable-cache: false
      ruleset-name: ""
      ruleset-format: ""
      download-detour: ""
      client-subnet: ""
    - id: ID_to65i9vk
      type: clash_mode
      payload: global
      server: remote-dns
      invert: false
      disable-cache: false
      ruleset-name: ""
      ruleset-format: ""
      download-detour: ""
      client-subnet: ""
    - id: ID_7jerss5o
      type: rule_set_url
      payload: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/cn.srs
      server: local-dns
      disable-cache: false
      invert: false
      ruleset-name: GEOSITE-CN
      ruleset-format: binary
      download-detour: ðŸŽ¯ Direct
      client-subnet: ""
    - id: ID_x6mvuowf
      type: rule_set_url
      payload: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/geolocation-!cn.srs
      server: remote-dns
      disable-cache: false
      invert: false
      ruleset-name: GEOLOCATION-!CN
      ruleset-format: binary
      download-detour: ðŸŽ¯ Direct
      client-subnet: ""
  mixinConfig:
    priority: mixin
    config: "{}"
  scriptConfig:
    code: |-
      const onGenerate = async (config) => {
        return config
      }
