- id: ID_hpaobjj7
  name: djzhang-subs
  upload: 0
  download: 0
  total: 0
  expire: 0
  updateTime: 1729262956550
  type: Manual
  website: ""
  path: data/subscribes/ID_hpaobjj7.json
  include: ""
  exclude: ""
  includeProtocol: ""
  excludeProtocol: direct|reject|selector|urltest|block|dns
  proxyPrefix: ""
  disabled: false
  inSecure: false
  userAgent: ""
  proxies:
    - id: ID_fh1a8n1r
      tag: åŠ å…¥æˆ‘çš„é¢‘é“t.me/CMLiussssè§£é”æ›´å¤šä¼˜é€‰èŠ‚ç‚¹
      type: vless
    - id: ID_e3qzcyl1
      tag: åä»£ä¼˜é€‰åŸŸå-å¤©åŸå¤§ä½¬æä¾›ç»´æŠ¤
      type: vless
    - id: ID_z2agyhvi
      tag: åä»£ä¼˜é€‰åŸŸå-Mingyuå¤§ä½¬æä¾›ç»´æŠ¤
      type: vless
    - id: ID_cwi95zrv
      tag: åä»£ä¼˜é€‰åŸŸå-OTCå¤§ä½¬æä¾›ç»´æŠ¤
      type: vless
    - id: ID_tq4r3u7r
      tag: åä»£ä¼˜é€‰åŸŸå-KJKKKå¤§ä½¬æä¾›ç»´æŠ¤
      type: vless
    - id: ID_a8n70hku
      tag: cdn-b100.â†—â†˜â†—.eu.orgåä»£ä¼˜é€‰åŸŸå
      type: vless
    - id: ID_9grifwb5
      tag: ğŸ‡¨ğŸ‡³ visa.cn
      type: vless
    - id: ID_o4hinbql
      tag: www.wto.org
      type: vless
    - id: ID_l9yw7isu
      tag: ğŸ‡¸ğŸ‡¬ www.visa.com.sg
      type: vless
    - id: ID_dx6rmj9i
      tag: ğŸ‡¨ğŸ‡³ icook.tw
      type: vless
    - id: ID_oeo5mes0
      tag: ğŸ‡­ğŸ‡° HK
      type: vless
    - id: ID_xy5etjve
      tag: ğŸ‡­ğŸ‡° HK 2
      type: vless
    - id: ID_lzey90ok
      tag: ğŸ‡­ğŸ‡° HK 3
      type: vless
    - id: ID_xaaa78yd
      tag: ğŸ‡­ğŸ‡° HK 4
      type: vless
    - id: ID_vf3c8ktm
      tag: ğŸ‡°ğŸ‡· KR
      type: vless
    - id: ID_t7lv7hjo
      tag: ğŸ‡ºğŸ‡¸ US
      type: vless
    - id: ID_ia00ntv0
      tag: ğŸ‡¸ğŸ‡¬ SG
      type: vless
    - id: ID_wvdvdai1
      tag: ğŸ‡°ğŸ‡· KR 2
      type: vless
    - id: ID_21uhaatd
      tag: ğŸ‡¸ğŸ‡¬ SG 2
      type: vless
    - id: ID_yorahqk0
      tag: ğŸ‡ºğŸ‡¸ US 2
      type: vless
    - id: ID_9b5uwm7t
      tag: ğŸ‡·ğŸ‡º RU
      type: vless
    - id: ID_tsbeq1eq
      tag: ğŸ‡ºğŸ‡¸ US 3
      type: vless
    - id: ID_m9c9b9g1
      tag: ğŸ‡ºğŸ‡¸ US 4
      type: vless
    - id: ID_zg5ppuif
      tag: ğŸ‡ºğŸ‡¸ US 5
      type: vless
    - id: ID_inm4xrp1
      tag: ğŸ‡¬ğŸ‡§ GB
      type: vless
    - id: ID_dwukgj7r
      tag: ZA
      type: vless
    - id: ID_s3jbx8e4
      tag: ğŸ‡ºğŸ‡¸ US 6
      type: vless
    - id: ID_p35ocew0
      tag: ğŸ‡ºğŸ‡¸ US 7
      type: vless
    - id: ID_ch8r0fjm
      tag: ğŸ‡¸ğŸ‡¬ SG 3
      type: vless
    - id: ID_s6f5tw5f
      tag: ğŸ‡ºğŸ‡¸ US 8
      type: vless
    - id: ID_8lqdmc8h
      tag: ğŸ‡ºğŸ‡¸ US 9
      type: vless
