proxies:
  - name: åŠ å…¥æˆ‘çš„é¢‘é“t.me/CMLiussssè§£é”æ›´å¤šä¼˜é€‰èŠ‚ç‚¹
    server: Join.my.Telegram.channel.CMLiussss.to.unlock.more.premium.nodes.cf.090227.xyz
    port: 80
    type: vless
    uuid: 4440a1c3-06dc-493b-a630-c6cc9a1dfb43
    tls: false
    tfo: false
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /?ed=2560&proxyip=proxyip.us.fxxk.dedyn.io
      headers:
        Host: djzhang.trujunzhang.workers.dev
  - name: åä»£ä¼˜é€‰åŸŸå-å¤©åŸå¤§ä½¬æä¾›ç»´æŠ¤
    server: aliyu.gitgoogle.com
    port: 2095
    type: vless
    uuid: 4440a1c3-06dc-493b-a630-c6cc9a1dfb43
    tls: false
    tfo: false
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /?ed=2560&proxyip=proxyip.digitalocean.fxxk.dedyn.io
      headers:
        Host: djzhang.trujunzhang.workers.dev
  - name: åä»£ä¼˜é€‰åŸŸå-Mingyuå¤§ä½¬æä¾›ç»´æŠ¤
    server: bestproxy.onecf.eu.org
    port: 80
    type: vless
    uuid: 4440a1c3-06dc-493b-a630-c6cc9a1dfb43
    tls: false
    tfo: false
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /?ed=2560&proxyip=proxyip.digitalocean.fxxk.dedyn.io
      headers:
        Host: djzhang.trujunzhang.workers.dev
  - name: åä»£ä¼˜é€‰åŸŸå-OTCå¤§ä½¬æä¾›ç»´æŠ¤
    server: proxy.xxxxxxxx.tk
    port: 80
    type: vless
    uuid: 4440a1c3-06dc-493b-a630-c6cc9a1dfb43
    tls: false
    tfo: false
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /?ed=2560&proxyip=proxyip.digitalocean.fxxk.dedyn.io
      headers:
        Host: djzhang.trujunzhang.workers.dev
  - name: åä»£ä¼˜é€‰åŸŸå-KJKKKå¤§ä½¬æä¾›ç»´æŠ¤
    server: acjp.cloudflarest.link
    port: 2052
    type: vless
    uuid: 4440a1c3-06dc-493b-a630-c6cc9a1dfb43
    tls: false
    tfo: false
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /?ed=2560&proxyip=proxyip.digitalocean.fxxk.dedyn.io
      headers:
        Host: djzhang.trujunzhang.workers.dev
  - name: cdn-b100.â†—â†˜â†—.eu.orgåä»£ä¼˜é€‰åŸŸå
    server: cdn-b100.xn--b6gac.eu.org
    port: 80
    type: vless
    uuid: 4440a1c3-06dc-493b-a630-c6cc9a1dfb43
    tls: false
    tfo: false
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /?ed=2560&proxyip=proxyip.digitalocean.fxxk.dedyn.io
      headers:
        Host: djzhang.trujunzhang.workers.dev
  - name: ğŸ‡¨ğŸ‡³ visa.cn
    server: visa.cn
    port: 80
    type: vless
    uuid: 4440a1c3-06dc-493b-a630-c6cc9a1dfb43
    tls: false
    tfo: false
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /?ed=2560&proxyip=proxyip.digitalocean.fxxk.dedyn.io
      headers:
        Host: djzhang.trujunzhang.workers.dev
  - name: www.wto.org
    server: www.wto.org
    port: 80
    type: vless
    uuid: 4440a1c3-06dc-493b-a630-c6cc9a1dfb43
    tls: false
    tfo: false
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /?ed=2560&proxyip=proxyip.digitalocean.fxxk.dedyn.io
      headers:
        Host: djzhang.trujunzhang.workers.dev
  - name: ğŸ‡¸ğŸ‡¬ www.visa.com.sg
    server: www.visa.com.sg
    port: 80
    type: vless
    uuid: 4440a1c3-06dc-493b-a630-c6cc9a1dfb43
    tls: false
    tfo: false
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /?ed=2560&proxyip=proxyip.sg.fxxk.dedyn.io
      headers:
        Host: djzhang.trujunzhang.workers.dev
  - name: ğŸ‡¨ğŸ‡³ icook.tw
    server: icook.tw
    port: 80
    type: vless
    uuid: 4440a1c3-06dc-493b-a630-c6cc9a1dfb43
    tls: false
    tfo: false
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /?ed=2560&proxyip=proxyip.tw.fxxk.dedyn.io
      headers:
        Host: djzhang.trujunzhang.workers.dev
  - name: ğŸ‡­ğŸ‡° HK
    server: 47.243.48.169
    port: 80
    type: vless
    uuid: 4440a1c3-06dc-493b-a630-c6cc9a1dfb43
    tls: false
    tfo: false
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /?ed=2560&proxyip=proxyip.aliyun.fxxk.dedyn.io
      headers:
        Host: djzhang.trujunzhang.workers.dev
  - name: ğŸ‡­ğŸ‡° HK 2
    server: 8.210.173.151
    port: 80
    type: vless
    uuid: 4440a1c3-06dc-493b-a630-c6cc9a1dfb43
    tls: false
    tfo: false
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /?ed=2560&proxyip=proxyip.aliyun.fxxk.dedyn.io
      headers:
        Host: djzhang.trujunzhang.workers.dev
  - name: ğŸ‡­ğŸ‡° HK 3
    server: 8.212.12.98
    port: 80
    type: vless
    uuid: 4440a1c3-06dc-493b-a630-c6cc9a1dfb43
    tls: false
    tfo: false
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /?ed=2560&proxyip=proxyip.aliyun.fxxk.dedyn.io
      headers:
        Host: djzhang.trujunzhang.workers.dev
  - name: ğŸ‡°ğŸ‡· KR
    server: 64.110.83.80
    port: 80
    type: vless
    uuid: 4440a1c3-06dc-493b-a630-c6cc9a1dfb43
    tls: false
    tfo: false
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /?ed=2560&proxyip=proxyip.kr.fxxk.dedyn.io
      headers:
        Host: djzhang.trujunzhang.workers.dev
  - name: ğŸ‡«ğŸ‡· FR
    server: 185.16.110.143
    port: 2052
    type: vless
    uuid: 4440a1c3-06dc-493b-a630-c6cc9a1dfb43
    tls: false
    tfo: false
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /?ed=2560&proxyip=proxyip.digitalocean.fxxk.dedyn.io
      headers:
        Host: djzhang.trujunzhang.workers.dev
  - name: AT
    server: 212.183.88.35
    port: 2082
    type: vless
    uuid: 4440a1c3-06dc-493b-a630-c6cc9a1dfb43
    tls: false
    tfo: false
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /?ed=2560&proxyip=proxyip.digitalocean.fxxk.dedyn.io
      headers:
        Host: djzhang.trujunzhang.workers.dev
  - name: BR
    server: 185.133.35.40
    port: 2082
    type: vless
    uuid: 4440a1c3-06dc-493b-a630-c6cc9a1dfb43
    tls: false
    tfo: false
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /?ed=2560&proxyip=proxyip.digitalocean.fxxk.dedyn.io
      headers:
        Host: djzhang.trujunzhang.workers.dev
  - name: ğŸ‡·ğŸ‡º RU
    server: 45.67.215.117
    port: 2082
    type: vless
    uuid: 4440a1c3-06dc-493b-a630-c6cc9a1dfb43
    tls: false
    tfo: false
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /?ed=2560&proxyip=proxyip.digitalocean.fxxk.dedyn.io
      headers:
        Host: djzhang.trujunzhang.workers.dev
  - name: ğŸ‡ºğŸ‡¸ US
    server: 192.0.54.251
    port: 2052
    type: vless
    uuid: 4440a1c3-06dc-493b-a630-c6cc9a1dfb43
    tls: false
    tfo: false
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /?ed=2560&proxyip=proxyip.us.fxxk.dedyn.io
      headers:
        Host: djzhang.trujunzhang.workers.dev
  - name: ğŸ‡ºğŸ‡¸ US 2
    server: 192.0.54.68
    port: 2052
    type: vless
    uuid: 4440a1c3-06dc-493b-a630-c6cc9a1dfb43
    tls: false
    tfo: false
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /?ed=2560&proxyip=proxyip.us.fxxk.dedyn.io
      headers:
        Host: djzhang.trujunzhang.workers.dev
  - name: ğŸ‡ºğŸ‡¸ US 3
    server: 63.141.128.67
    port: 2082
    type: vless
    uuid: 4440a1c3-06dc-493b-a630-c6cc9a1dfb43
    tls: false
    tfo: false
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /?ed=2560&proxyip=proxyip.us.fxxk.dedyn.io
      headers:
        Host: djzhang.trujunzhang.workers.dev
  - name: ğŸ‡¸ğŸ‡¬ SG
    server: 206.238.236.118
    port: 2082
    type: vless
    uuid: 4440a1c3-06dc-493b-a630-c6cc9a1dfb43
    tls: false
    tfo: false
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /?ed=2560&proxyip=proxyip.sg.fxxk.dedyn.io
      headers:
        Host: djzhang.trujunzhang.workers.dev
  - name: ğŸ‡¸ğŸ‡¬ SG 2
    server: 206.238.237.250
    port: 2082
    type: vless
    uuid: 4440a1c3-06dc-493b-a630-c6cc9a1dfb43
    tls: false
    tfo: false
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /?ed=2560&proxyip=proxyip.sg.fxxk.dedyn.io
      headers:
        Host: djzhang.trujunzhang.workers.dev
  - name: ğŸ‡·ğŸ‡º RU 2
    server: 45.67.215.121
    port: 2052
    type: vless
    uuid: 4440a1c3-06dc-493b-a630-c6cc9a1dfb43
    tls: false
    tfo: false
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /?ed=2560&proxyip=proxyip.digitalocean.fxxk.dedyn.io
      headers:
        Host: djzhang.trujunzhang.workers.dev
  - name: ğŸ‡·ğŸ‡º RU 3
    server: 45.67.215.23
    port: 2052
    type: vless
    uuid: 4440a1c3-06dc-493b-a630-c6cc9a1dfb43
    tls: false
    tfo: false
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /?ed=2560&proxyip=proxyip.digitalocean.fxxk.dedyn.io
      headers:
        Host: djzhang.trujunzhang.workers.dev
  - name: ğŸ‡¬ğŸ‡§ GB
    server: 217.163.76.123
    port: 2082
    type: vless
    uuid: 4440a1c3-06dc-493b-a630-c6cc9a1dfb43
    tls: false
    tfo: false
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /?ed=2560&proxyip=proxyip.digitalocean.fxxk.dedyn.io
      headers:
        Host: djzhang.trujunzhang.workers.dev
  - name: ğŸ‡ºğŸ‡¸ US 4
    server: 158.224.83.140
    port: 2082
    type: vless
    uuid: 4440a1c3-06dc-493b-a630-c6cc9a1dfb43
    tls: false
    tfo: false
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /?ed=2560&proxyip=proxyip.us.fxxk.dedyn.io
      headers:
        Host: djzhang.trujunzhang.workers.dev
  - name: ğŸ‡ºğŸ‡¸ US 5
    server: 130.250.137.190
    port: 2052
    type: vless
    uuid: 4440a1c3-06dc-493b-a630-c6cc9a1dfb43
    tls: false
    tfo: false
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /?ed=2560&proxyip=proxyip.us.fxxk.dedyn.io
      headers:
        Host: djzhang.trujunzhang.workers.dev
