- id: ID_7slmx42f
  name: DJZHANG_Subs
  url: ""
  upload: 0
  download: 0
  total: 0
  expire: 0
  updateTime: 1729334891683
  type: Manual
  website: ""
  path: data/subscribes/ID_7slmx42f.json
  include: ""
  exclude: ""
  includeProtocol: ""
  excludeProtocol: direct|reject|selector|urltest|block|dns
  proxyPrefix: ""
  disabled: false
  inSecure: false
  userAgent: ""
  proxies:
    - id: ID_hvdjoco6
      tag: åŠ å…¥æˆ‘çš„é¢‘é“t.me/CMLiussssè§£é”æ›´å¤šä¼˜é€‰èŠ‚ç‚¹
      type: vless
    - id: ID_6hby9zkh
      tag: åä»£ä¼˜é€‰åŸŸå-å¤©åŸå¤§ä½¬æä¾›ç»´æŠ¤
      type: vless
    - id: ID_ib128pn5
      tag: åä»£ä¼˜é€‰åŸŸå-Mingyuå¤§ä½¬æä¾›ç»´æŠ¤
      type: vless
    - id: ID_diqvmzxk
      tag: åä»£ä¼˜é€‰åŸŸå-OTCå¤§ä½¬æä¾›ç»´æŠ¤
      type: vless
    - id: ID_6y4lpl8e
      tag: åä»£ä¼˜é€‰åŸŸå-KJKKKå¤§ä½¬æä¾›ç»´æŠ¤
      type: vless
    - id: ID_1qsnsoel
      tag: cdn-b100.â†—â†˜â†—.eu.orgåä»£ä¼˜é€‰åŸŸå
      type: vless
    - id: ID_iyoi9k0n
      tag: ğŸ‡¨ğŸ‡³ visa.cn
      type: vless
    - id: ID_ik5tfmpf
      tag: www.wto.org
      type: vless
    - id: ID_09zki160
      tag: ğŸ‡¸ğŸ‡¬ www.visa.com.sg
      type: vless
    - id: ID_k09q84ex
      tag: ğŸ‡¨ğŸ‡³ icook.tw
      type: vless
    - id: ID_wf63t2nw
      tag: ğŸ‡­ğŸ‡° HK
      type: vless
    - id: ID_ejozkzlu
      tag: ğŸ‡­ğŸ‡° HK 2
      type: vless
    - id: ID_i47xhnf7
      tag: ğŸ‡­ğŸ‡° HK 3
      type: vless
    - id: ID_a0ecdhpp
      tag: ğŸ‡­ğŸ‡° HK 4
      type: vless
    - id: ID_eo1r2gtu
      tag: AE
      type: vless
    - id: ID_9rxzd5u1
      tag: BR
      type: vless
    - id: ID_o7bvaj3u
      tag: ğŸ‡ºğŸ‡¸ US
      type: vless
    - id: ID_6d9stlv6
      tag: ğŸ‡·ğŸ‡º RU
      type: vless
    - id: ID_ckzndlin
      tag: ğŸ‡ºğŸ‡¸ US 2
      type: vless
    - id: ID_lttg153x
      tag: ğŸ‡ºğŸ‡¸ US 3
      type: vless
    - id: ID_eb34rtpz
      tag: AT
      type: vless
    - id: ID_wlujvqdi
      tag: ZA
      type: vless
    - id: ID_zigh61a7
      tag: ZA 2
      type: vless
    - id: ID_obxy7qfp
      tag: ğŸ‡ºğŸ‡¸ US 4
      type: vless
    - id: ID_8m4mf2k7
      tag: ğŸ‡¸ğŸ‡¬ SG
      type: vless
    - id: ID_wys3bsh9
      tag: ğŸ‡·ğŸ‡º RU 2
      type: vless
    - id: ID_bxzfp5mj
      tag: ğŸ‡ºğŸ‡¸ US 5
      type: vless
    - id: ID_mzkwscsd
      tag: ZA 3
      type: vless
    - id: ID_yaim2hhv
      tag: ZA 4
      type: vless
    - id: ID_zrcuh0ln
      tag: ZA 5
      type: vless
    - id: ID_c235qykq
      tag: ğŸ‡ºğŸ‡¸ US 6
      type: vless
