- id: ID_5bo80cd6
  name: wanghao
  url: ""
  upload: 6543782699165
  download: 6543782699165
  total: 26388279066624
  expire: 4102329600000
  updateTime: 1759233251487
  type: Manual
  website: ""
  path: data/subscribes/ID_5bo80cd6.json
  include: ""
  exclude: ""
  includeProtocol: ""
  excludeProtocol: direct|reject|selector|urltest|block|dns|shadowsocksr
  proxyPrefix: ""
  disabled: false
  inSecure: false
  requestMethod: GET
  header:
    request: {}
    response: {}
  proxies:
    - id: ID_hfh8efh6
      tag: wh1
      type: vless
    - id: ID_6pcghs1n
      tag: wh2
      type: vless
    - id: ID_rdhmvwho
      tag: wh3
      type: vless
    - id: ID_we28p3ha
      tag: ðŸ‡¨ðŸ‡³ visa.cn
      type: vless
    - id: ID_a0ig1i14
      tag: ðŸ‡ºðŸ‡¸ US
      type: vless
    - id: ID_7s2livv5
      tag: ðŸ‡¸ðŸ‡¬ SG
      type: vless
    - id: ID_sia0c3l7
      tag: ðŸ‡¸ðŸ‡¬ SG 2
      type: vless
    - id: ID_52u0ykvt
      tag: ðŸ‡¸ðŸ‡¬ SG 3
      type: vless
    - id: ID_zmqv46z9
      tag: CFä¼˜é€‰
      type: vless
    - id: ID_dnjbdkqk
      tag: CFä¼˜é€‰ 2
      type: vless
    - id: ID_9ju9lwyh
      tag: CFä¼˜é€‰ 3
      type: vless
    - id: ID_fg5nix39
      tag: CFä¼˜é€‰ 4
      type: vless
    - id: ID_9kjkb23v
      tag: CFä¼˜é€‰ 5
      type: vless
    - id: ID_yqdjdk5g
      tag: CFä¼˜é€‰ 6
      type: vless
    - id: ID_hzljrqyo
      tag: CFä¼˜é€‰ 7
      type: vless
    - id: ID_ac6aan8f
      tag: CFä¼˜é€‰ 8
      type: vless
    - id: ID_u79pp4hm
      tag: CFä¼˜é€‰ 9
      type: vless
    - id: ID_64y9cdda
      tag: CFä¼˜é€‰ 10
      type: vless
    - id: ID_hpkbub5q
      tag: CFä¼˜é€‰ 11
      type: vless
    - id: ID_6dipnsk3
      tag: CFä¼˜é€‰ 12
      type: vless
    - id: ID_o4g0v4rk
      tag: CFä¼˜é€‰ 13
      type: vless
    - id: ID_shyd7g7o
      tag: CFä¼˜é€‰ 14
      type: vless
    - id: ID_3u60h31y
      tag: CFä¼˜é€‰ 15
      type: vless
    - id: ID_re5l3r7h
      tag: CFä¼˜é€‰ 16
      type: vless
    - id: ID_6xyegtm6
      tag: CFä¼˜é€‰ 17
      type: vless
    - id: ID_dbi8o0bn
      tag: CFä¼˜é€‰ 18
      type: vless
    - id: ID_o50ft0p2
      tag: CFä¼˜é€‰ 19
      type: vless
    - id: ID_p6pkq1to
      tag: CFä¼˜é€‰ 20
      type: vless
    - id: ID_aufoit53
      tag: CFä¼˜é€‰ 21
      type: vless
    - id: ID_rikeoioi
      tag: CFä¼˜é€‰ 22
      type: vless
    - id: ID_t4tng0ew
      tag: CFä¼˜é€‰ 23
      type: vless
  script: |-
    const onSubscribe = async (proxies, subscription) => {
      return { proxies, subscription }
    }
  requestTimeout: 15
