- id: ID_lo8t72vx
  name: djzhang-subs
  useInternal: false
  url: ""
  upload: 1295370993650
  download: 1295370993650
  total: 26388279066624
  expire: 4102329600000
  updateTime: 1729304482889
  type: Manual
  website: ""
  path: data/subscribes/ID_lo8t72vx.yaml
  include: ""
  exclude: ""
  includeProtocol: ""
  excludeProtocol: ""
  proxyPrefix: ""
  disabled: false
  inSecure: false
  userAgent: ""
  healthCheck:
    enable: false
    url: https://www.gstatic.com/generate_204
    interval: 300
  proxies:
    - id: ID_hweh781i
      name: åŠ å…¥æˆ‘çš„é¢‘é“t.me/CMLiussssè§£é”æ›´å¤šä¼˜é€‰èŠ‚ç‚¹
      type: vless
    - id: ID_6gh2e57l
      name: åä»£ä¼˜é€‰åŸŸå-å¤©åŸå¤§ä½¬æä¾›ç»´æŠ¤
      type: vless
    - id: ID_0cyyva5w
      name: åä»£ä¼˜é€‰åŸŸå-Mingyuå¤§ä½¬æä¾›ç»´æŠ¤
      type: vless
    - id: ID_wj64f5fs
      name: åä»£ä¼˜é€‰åŸŸå-OTCå¤§ä½¬æä¾›ç»´æŠ¤
      type: vless
    - id: ID_3ir8yx95
      name: åä»£ä¼˜é€‰åŸŸå-KJKKKå¤§ä½¬æä¾›ç»´æŠ¤
      type: vless
    - id: ID_orgp7ur3
      name: cdn-b100.â†—â†˜â†—.eu.orgåä»£ä¼˜é€‰åŸŸå
      type: vless
    - id: ID_5al9du79
      name: ğŸ‡¨ğŸ‡³ visa.cn
      type: vless
    - id: ID_4cbzxssw
      name: www.wto.org
      type: vless
    - id: ID_y7gyvn4i
      name: ğŸ‡¸ğŸ‡¬ www.visa.com.sg
      type: vless
    - id: ID_yyjlyzcw
      name: ğŸ‡¨ğŸ‡³ icook.tw
      type: vless
    - id: ID_0koqi258
      name: ğŸ‡­ğŸ‡° HK
      type: vless
    - id: ID_j0acrnrt
      name: ğŸ‡­ğŸ‡° HK 2
      type: vless
    - id: ID_2mqxjltl
      name: ğŸ‡­ğŸ‡° HK 3
      type: vless
    - id: ID_od64me1m
      name: ğŸ‡°ğŸ‡· KR
      type: vless
    - id: ID_uxzqhscf
      name: ğŸ‡«ğŸ‡· FR
      type: vless
    - id: ID_vc3l11e4
      name: AT
      type: vless
    - id: ID_wychgt60
      name: BR
      type: vless
    - id: ID_bbayq03l
      name: ğŸ‡·ğŸ‡º RU
      type: vless
    - id: ID_ndklfjgm
      name: ğŸ‡ºğŸ‡¸ US
      type: vless
    - id: ID_29zvxzym
      name: ğŸ‡ºğŸ‡¸ US 2
      type: vless
    - id: ID_sfqys9l8
      name: ğŸ‡¨ğŸ‡³ CN
      type: vless
    - id: ID_af56bn72
      name: ğŸ‡ºğŸ‡¸ US 3
      type: vless
    - id: ID_dkvkwfmn
      name: ğŸ‡¸ğŸ‡¬ SG
      type: vless
    - id: ID_uf0vuyoc
      name: ğŸ‡¨ğŸ‡³ CN 2
      type: vless
    - id: ID_oss4iqa0
      name: ğŸ‡¸ğŸ‡¬ SG 2
      type: vless
    - id: ID_miqbdddj
      name: ğŸ‡·ğŸ‡º RU 2
      type: vless
    - id: ID_icptajrg
      name: ğŸ‡·ğŸ‡º RU 3
      type: vless
    - id: ID_d4yhk3sm
      name: ğŸ‡¬ğŸ‡§ GB
      type: vless
    - id: ID_ddjmyodv
      name: ğŸ‡ºğŸ‡¸ US 4
      type: vless
    - id: ID_df93cnti
      name: ğŸ‡ºğŸ‡¸ US 5
      type: vless
