- id: ID_2t1f7dsc
  name: hxyin-work-subscribes
  url: https://hxyin-work.yinhaixiadrop.workers.dev/4440a1c3-06dc-493b-a630-c6cc9a1dfb43?singbox
  upload: 0
  download: 0
  total: 0
  expire: 0
  updateTime: 1741180136022
  type: Manual
  website: ""
  path: data/subscribes/ID_2t1f7dsc.json
  include: ""
  exclude: ""
  includeProtocol: ""
  excludeProtocol: direct|reject|selector|urltest|block|dns|shadowsocksr
  proxyPrefix: ""
  disabled: false
  inSecure: false
  userAgent: ""
  proxies:
    - id: ID_9xrxd9ke
      tag: åŠ å…¥æˆ‘çš„é¢‘é“t.me/CMLiussssè§£é”æ›´å¤šä¼˜é€‰èŠ‚ç‚¹
      type: vless
    - id: ID_clqt22d1
      tag: åä»£ä¼˜é€‰åŸŸå-å¤©åŸå¤§ä½¬æä¾›ç»´æŠ¤
      type: vless
    - id: ID_qmg59kkn
      tag: åä»£ä¼˜é€‰åŸŸå-Mingyuå¤§ä½¬æä¾›ç»´æŠ¤
      type: vless
    - id: ID_88jggejd
      tag: åä»£ä¼˜é€‰åŸŸå-OTCå¤§ä½¬æä¾›ç»´æŠ¤
      type: vless
    - id: ID_p7qmsl2d
      tag: åä»£ä¼˜é€‰åŸŸå-KJKKKå¤§ä½¬æä¾›ç»´æŠ¤
      type: vless
    - id: ID_5f8sjwvp
      tag: cdn-b100.â†—â†˜â†—.eu.orgåä»£ä¼˜é€‰åŸŸå
      type: vless
    - id: ID_2oouzej7
      tag: ğŸ‡¨ğŸ‡³ visa.cn
      type: vless
    - id: ID_gnemq6gl
      tag: www.wto.org
      type: vless
    - id: ID_4p9ei2sr
      tag: ğŸ‡¸ğŸ‡¬ www.visa.com.sg
      type: vless
    - id: ID_c95n4tha
      tag: ğŸ‡¨ğŸ‡³ icook.tw
      type: vless
    - id: ID_4z1yagn9
      tag: ğŸ‡­ğŸ‡° HK
      type: vless
    - id: ID_84u63auz
      tag: ğŸ‡­ğŸ‡° HK 2
      type: vless
    - id: ID_jvwsyw36
      tag: ğŸ‡­ğŸ‡° HK 3
      type: vless
    - id: ID_jjb8vh5m
      tag: ğŸ‡­ğŸ‡° HK 4
      type: vless
    - id: ID_hpmwk82x
      tag: AE
      type: vless
    - id: ID_3s544blf
      tag: BR
      type: vless
    - id: ID_y8bn0cjb
      tag: ğŸ‡ºğŸ‡¸ US
      type: vless
    - id: ID_gjzhii9x
      tag: ğŸ‡·ğŸ‡º RU
      type: vless
    - id: ID_hg4bx273
      tag: ğŸ‡ºğŸ‡¸ US 2
      type: vless
    - id: ID_dca1j02a
      tag: ğŸ‡ºğŸ‡¸ US 3
      type: vless
    - id: ID_t7sc7jko
      tag: AT
      type: vless
    - id: ID_iwpyeynr
      tag: ZA
      type: vless
    - id: ID_wlouf1qo
      tag: ZA 2
      type: vless
    - id: ID_48zg13f4
      tag: ğŸ‡ºğŸ‡¸ US 4
      type: vless
    - id: ID_3i1b3xlz
      tag: ğŸ‡¸ğŸ‡¬ SG
      type: vless
    - id: ID_xkdmytl7
      tag: ğŸ‡·ğŸ‡º RU 2
      type: vless
    - id: ID_5lb7qubf
      tag: ğŸ‡ºğŸ‡¸ US 5
      type: vless
    - id: ID_r5nshzxp
      tag: ZA 3
      type: vless
    - id: ID_o6tqb5i7
      tag: ZA 4
      type: vless
    - id: ID_qzynzgec
      tag: ZA 5
      type: vless
    - id: ID_vt9rlct3
      tag: ğŸ‡ºğŸ‡¸ US 6
      type: vless
